[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xxxxx-project-name"
version = "0.0.1"
description = "xxxxx_project_description"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "Avi Zaguri" },]
keywords = [
    "development",
    "python",
    "pytest",
    "xxxxx_project_keywords"
]

classifiers = [
    # "Development Status :: 5 - Production/Stable",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "setuptools",
    "wheel",
    "dotenv",
    "custom-python-logger",
]

[project.urls]
Homepage = "https://github.com/aviz92/xxxxx-project-name"
Repository = "https://github.com/aviz92/xxxxx-project-name"
Issues = "https://github.com/aviz92/xxxxx-project-name/issues"

[tool.setuptools.packages.find]
where = ["."]
# include = ["xxxxx_project_name*"]
namespaces = false

[project.scripts]  # must using "uv sync" or "uv pip install -e ." first
clean_pycache = "scripts.clean__pycache__:main"
run_pytest_marker = "scripts.ci.run_pytest_marker:main"
clean_migrations = "scripts.django.clean_migrations:main"
